language: bash

dist: trusty
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan wget -y

script:
    - gem install fpm
    - ./create_packages
    - ./ci_test

notifications:
  email:
    recipients:
      - ms-travisci@256bit.org
    on_success: change
    on_failure: always

deploy:
  provider: releases
  #api_key: "GITHUB OAUTH TOKEN"
  file: "zabbix-agent-extensions_*_all.deb"
  file: "zabbix-agent-extensions-*.noarch.rpm"
  skip_cleanup: true
  on:
    tags: true

