language: bash

before_script:
    - find / -name "README.md"
    - sudo apt-get install ruby-dev build-essential debhelper devscripts rpm
    - gem install fpm --user
    - wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-agent_3.2.8-1+xenial_amd64.deb
    - dpkg -i zabbix-agent_*_amd64.deb

script:
    - ./create_packages
    - dpkg -i zabbix-agent-extensions_*_all.deb
