language: bash

before_script:
    - sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan -y
    - gem install fpm --user
    - wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-agent_3.2.8-1+xenial_amd64.deb
    - sudo dpkg -i zabbix-agent_*_amd64.deb

script:
    - PATH=/home/travis/.gem/ruby/2.4.0/bin:$PATH ./create_packages
    - ./ci_test.sh
    
# https://docs.travis-ci.com/user/deployment/releases/
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

