language: bash

before_script:
    - sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan -y
    - sudo gem install fpm
    - wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix/zabbix-agent_3.2.8-1+xenial_amd64.deb
    - sudo dpkg -i zabbix-agent_*_amd64.deb

script:
    - ./create_packages
    - sudo dpkg -i zabbix-agent-extensions_*_all.deb

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

