language: bash

before_script:
    - sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan -y
    - gem install fpm --user

script:
    - ./create_packages
    - pwd
    - ls -l 
    - ./ci_test

notifications:
  email:
    recipients:
      - ms-travisci@256bit.org
    on_success: change
    on_failure: always

# https://docs.travis-ci.com/user/deployment/releases/
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

