language: bash

dist: trusty
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan wget -y

script:
    - gem install fpm
    - env
    - type -a fpm
    - fpm --help
    - ./create_packages
    - ./ci_test

notifications:
  email:
    recipients:
      - ms-travisci@256bit.org
    on_success: change
    on_failure: always

# https://docs.travis-ci.com/user/deployment/releases/
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true

